### ISSUE TITLE
Return more info when KeyErrors in action_load and action_unload

### ISSUE THREAD

**Issue by lmzxqtom** [martinslabber/tape-library-robot-control#1]
It would be nice to get a better message when entering invalid slot and drive:
500 Internal Server Error
Server got itself in trouble

Perhaps catching the key error and returning a useful message:
```
try:
    slot_class = self.slots[slot]
except KeyError:
    return "Invalid slot name {}, e.g. {}".format(slot, [*self.slots][0])
try: 
   drive_class = self.drives[drive]
except KeyError:
    return "Invalid drive {}, e.g. {}".format(drive, [*self.drives][0])
```

**Comment by martinslabber** [comment]
Thank you. I'll implement a generic error handling an output then all errors will be formatted the same. At the moment the return codes are also not as it should be I'll stick to rfc2616.

**Comment by martinslabber** [comment]
A generic error handling function was added. All the Library API calls go through this error handling function. The simulator calls do not, they bomb out with Python errors (nasty but helps to distinguish between them).  The swagger docs still need to be updated, I need to look for a more generic way of doing it since I don't want to edit each docstring.
